---
#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

# Use this Antora Playbook for publication, to build the released version branch.
site:
  title: Eclipse Che Documentation
  # The url property is mandatory to generate the 404 and sitemap files.
  url: https://www.eclipse.org/che
  start_page: docs:overview:introduction-to-eclipse-che.adoc
  keys:
    google_analytics: "UA-37306001-2"
content:
  sources:
    - url: https://github.com/eclipse/che-docs
      branches:
        - "7.46.x"
        - "7.43.x"
        - master
      edit_url: "{web_url}/edit/{refname}/{path}"
antora:
  extensions:
    - require: "@antora/lunr-extension"
asciidoc:
  sourcemap: true
output:
  destinations:
    - provider: fs
      clean: true
      path: build/site
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
  output_dir: docs/_
urls:
  html_extension_style: indexify
  latest_prerelease_version_segment: next
  latest_version_segment: stable
  latest_version_segment_strategy: replace
  redirect_facility: static
runtime:
  cache_dir: ./.cache/antora
  fetch: true
  log:
    failure_level: warn
    level: info
