#
# Copyright (c) 2012-2017 Red Hat, Inc.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

markdown: kramdown
highlighter: rouge


kramdown:
  toc_levels:     1..1
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM

repository: https://github.com/eclipse/che-docs/
#help_url: https://github.com/jekyll/jekyll-help

timezone: America/Los_Angeles

collections:
  docs:
    output: true
  tutorials:
    output: true
  openshift:
    output: true

name: Eclipse Che Docs
description: Cloud workspaces for development teams
url: https://www.eclipse.org/che/

product_name: "CHE"
product_mini_name:  "Che"
product_mini_cli: "che"
product_formal_name: "Eclipse Che"

twitter:
  username: eclipse_che

logo: /img/logo-2x.png

exclude:
  - /dev/
  - README.md
  - .gitignore
  - docs.sh
  - assembly/*
  - _site/*
  - pom.xml

 # The following are used to define markdown permalinks
defaults:
  -
    scope:
      path: "_docs/assemblies"
    values:
      categories: [ "docs" , "assemblies" ]
  -
    scope:
      path: "_docs/devops"
    values:
      categories: [ "docs" , "devops" ]
  -
    scope:
      path: "_docs/ide"
    values:
      categories: [ "docs" , "ide" ]
  -
    scope:
      path: "_docs/openshift"
    values:
      categories: [ "docs" , "openshift" ]
  -
    scope:
      path: "_docs/setup"
    values:
      categories: [ "docs" , "setup" ]
  -
    scope:
      path: "_docs/tutorials"
    values:
      categories: [ "docs" , "tutorials" ]
  -
    scope:
      path: "_docs/chedir-portable-workspaces"
    values:
      categories: [ "docs" , "chedir"]
  -
    scope:
      path: "_docs/factory-portable-workspaces"
    values:
      categories: [ "docs" , "factory"]
  -
    scope:
      path: "_docs/che-data-model"
    values:
      categories: [ "docs" , "data-model" ]
  -
    scope:
      path: "_docs/user-management"
    values:
      categories: [ "docs" , "user-management" ]
