repository: eclipse/che

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: Eclipse Che Documentation
# this appears on the top navigation bar next to the home button

site_title: Eclipse Che Documentation
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: Eclipse Che
# this appears in the footer

# github_editme_path: tomjoht/documentation-theme-jekyll/blob/gh-pages/
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

# gitlab_editme_path: tomjoht/documentation-theme-jekyll/blob/gh-pages/
# if you're using GitLab, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

# disqus_shortname: idrbwjekyll
# if you're using disqus for comments, add the shortname here. if not, leave this value blank.

# google_analytics: UA-66296557-1
# if you have google-analytics ID, put it in. if not, edit this value to blank.

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4000
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

exclude:
  - .idea/
  - .gitignore
  - vendor
# these are the files and directories that jekyll will exclude from the build

plugins:
  - jekyll-asciidoc
  - jekyll-redirect-from

asciidoc_attributes: &asciidoc_attributes
  project-context: che
  prod: Eclipse Che
  prod2: Eclipse Che
  prod-short: Che
  prod-id: eclipse-che
  prod-id-short: che
  prod-prev-ver: 6.x
  prod-ver: 7.9
  prod-cli: chectl
  orch-cli: kubectl
  prod-checluster: eclipse-che
  prod-namespace: default
  prod-url: http(s)://che-host:che-port
  prod-url-secure: http(s)://che-che
  prod-host: che-host
  ocp: OpenShift Container Platform
  prod-deployment: che
  prod-operator: che-operator
# // URLs for the Downstream synergy
  link-accessing-a-git-repository-via-https: link:{site-baseurl}che-7/version-control/#accessing-a-git-repository-via-https_version-control[Accessing a Git repository via HTTPS]
  link-limits-for-the-workspaces-of-an-user: link:{site-baseurl}che-7/advanced-configuration-options/#limits-for-the-workspaces-of-an-user[Limits for the workspaces of an user]
  link-viewing-the-state-of-the-cluster-deployment-using-openshift-4-cli-tools: link:{site-baseurl}che-7/installing-che-on-openshift-4-from-operatorhub/#viewing-the-state-of-the-che-cluster-deployment-using-openshift-4-cli-tools_installing-che-on-openshift-4-from-operatorhub[Viewing the state of the {prod-short} cluster deployment using OpenShift 4 CLI tools]
  link-building-a-custom-plug-in-registry: link:{site-baseurl}che-7/building-and-running-a-custom-registry-image/#building-a-custom-devfile-registry_building-and-running-a-custom-registry-image[Building a custom plug-in registry]
  link-cli-github: https://github.com/che-incubator/chectl
  identity-provider-docs-url: https://www.keycloak.org/docs/
  identity-provider-version: 6.0
  identity-provider: Keycloak
  identity-provider-url: https://www.keycloak.org/
  identity-provider2: Keycloak
  image-puller: quay.io/eclipse/kubernetes-image-puller 
  image-puller-tag: latest

  imagesdir: /images
  site-baseurl: /
  page-liquid: ''
  source-highlighter: coderay
  coderay-css: style
  icons: font
  experimental: ''

asciidoc:
  require_front_matter_header: true
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes: *asciidoc_attributes

# library used for syntax highlighting

collections:
  tooltips:
    output: false
# collections are declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output unless you change output to true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: che_6_docs
      topnav: topnav
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true
      sidebar: home_sidebar
      topnav: topnav

# these are defaults used for the frontmatter for these file types

sidebars:
- che_7_docs

description: "Intended as a documentation theme based on Jekyll for technical writers documenting software and other technical products, this theme has all the elements you would need to handle multiple products with both multi-level sidebar navigation, tags, and other documentation features."
# the description is used in the feed.xml file

# needed for sitemap.xml file only
# url: http://idratherbewriting.com

# custom vars
baseurl: "/"
latest_6_x_version: "6.19.0"
