#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: build-documentation-pr
on: pull_request
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: build
        id: antora-build
        run: |
           yarn
           ./node_modules/.bin/antora generate antora-playbook.yml
      - uses: actions/upload-artifact@v2
        with:
          name: doc-content
          path: build/site
      - name: Store PR info
        run: |
          echo "${{ github.event.number }}" > PR_NUMBER
          echo "${{ github.event.pull_request.head.sha }}" > PR_SHA
      - uses: actions/upload-artifact@v2
        with:
          name: pull-request-number
          path: PR_NUMBER
      - uses: actions/upload-artifact@v2
        with:
          name: pull-request-sha
          path: PR_SHA
