#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

# GitHub Actions configuration file for htmltest
# See: https://github.com/wjdp/htmltest

name: Publication builder
on:
  # Reusable workflow
  workflow_call:
  # Manual run: 'Run workflow' button on the Actions tab
  workflow_dispatch:
  # Run when the publication-builder branch reeive a push
  push:
    branches:
      - publication-builder
      - main
      - "7.*"
  # Run at least one time per day
  schedule:
    - cron: "42 7 * * *"
  # Ideally, run when the main or release branch receive a push

jobs:
  build:
    name: Publication builder
    runs-on: ubuntu-20.04
    container: "quay.io/eclipse/che-docs:latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Cache for Antora UI and Htmltest.
      # See: https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows
      # Htmltest accepts 2 weeks old cache for the status code of checked external URLs
      # See: https://github.com/wjdp/htmltest
      # Refresh the cache every week to avoid a stale cache for htmltest
      # See: https://github.com/actions/cache
      # See: http://man7.org/linux/man-pages/man1/date.1.html
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=yearweek::$(/bin/date -u "+%Y%U")"
          echo "::set-output name=timestamp::$(/bin/date -Iminutes)"
        shell: bash
      - name: Restore cache
        uses: actions/cache@v2
        env:
          cache-name: cache
        with:
          path: .cache
          key: ${{ steps.get-date.outputs.yearweek }}

      - name: Build for publication
        id: antora-build
        run: tools/publication-builder.sh

      - name: Commit artifact to publication branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          commit_message: "Publication at ${{ steps.get-date.outputs.timestamp }}"
          force_orphan: true # publish branch with only the latest commit
          github_token: ${{ secrets.CHE_BOT_GITHUB_TOKEN }}
          publish_branch: publication
          publish_dir: build/site
