#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: vale-pr-check
on: [push, pull_request]
jobs:
  vale:
    name: check vale
    runs-on: ubuntu-20.04
    container: "quay.io/eclipse/che-docs:latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Vale
        run: |
          git fetch
          vale -v
          vale $(git diff --name-only origin/master)
          # git diff --name-only origin/master > changed-files.txt
          # for f in `cat changed-files.txt` ; do
          #   mkdir -p /tmp/vale/$(dirname $f)
          #   echo "-- extracting git changes from $f --"
          #   git diff --unified=0 origin/master -- $f | tail -n +6 | grep '^+' | sed 's/^+//' > /tmp/vale/$f
          # done
          # # Run vale on the delta changes
          # docker run --rm -v $(pwd):/docs -v /tmp/vale:/che-docs --entrypoint=sh jdkato/vale -c 'cd /docs && vale --sort /che-docs'
